FROM python:3.11.8-bookworm
WORKDIR /app
# Install Java (default JDK) and update packages
RUN apt-get update && apt-get install -y default-jdk
# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH=$JAVA_HOME/bin:$PATH

COPY . /app
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "ml_predict_from_kafka_stream.py"]
